# Generated by Django 4.0.1 on 2022-01-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='defaultgiftlogo.jpg', upload_to='product_images'),
        ),
    ]
